apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: verify
  labels:
    role: verify
    app: LocalEGA
spec:
  replicas: 1
  serviceName: verify
  selector:
    matchLabels:
      app: verify
  template:
    metadata:
      labels:
        app: verify
        role: verify
    spec:
      containers:
      - name: verify
        image: nbisweden/ega-base:latest
        imagePullPolicy: Always
        command: ["gosu", "lega", "ega-verify"]
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lega-db-secret
                key: postgres_password
          - name: LEGA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lega-password
                key: password
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-keys
                key: access_key
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: s3-keys
                key: secret_key
        volumeMounts:
        - name: verify-conf
          mountPath: /etc/ega
      restartPolicy: Always
      volumes:
      - name: verify-conf
        configMap:
          name: lega-config
          items:
            - key: conf.ini
              path: conf.ini
          defaultMode: 0744
