apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    role: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
        role: database
    spec:
      containers:
      - name: postgresql
        image: centos/postgresql-96-centos7
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - pg_isready -h 127.0.0.1 -p 5432 ;
                - psql -c "\i /postgresql-init/db.sql"
        env:
        - name: POSTGRESQL_USER
          valueFrom:
            configMapKeyRef:
              name: lega-db-config
              key: user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lega-db-secret
              key: postgres_password
        - name: POSTGRESQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: lega-db-config
              key: dbname
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/pgsql/data
        - mountPath: /postgresql-init
          name: initdb
        livenessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - pg_isready -h 127.0.0.1 -p 5432
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
        readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d
                  $POSTGRESQL_DATABASE -c 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: localega-db-storage
      - name: initdb
        configMap:
          name: initsql
