FROM egarchive/lega-inbox-os:latest
LABEL maintainer "EGA System Developers"

#################################################
##
## Install the notification system
##
#################################################

# These are enough
RUN pip3.6 install --upgrade pip && \
    pip3.6 install PyYaml pika==0.12.0 uvloop

COPY setup.py /root/LocalEGA/setup.py
COPY lega /root/LocalEGA/lega

RUN pip install /root/LocalEGA && \
    rm -rf /root/LocalEGA
