apiVersion: apps/v1
kind: Deployment
metadata:
  name: cega-users
  labels:
    role: fake-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cega-users
  template:
    metadata:
      labels:
        app: cega-users
        role: fake-users
    spec:
      containers:
      - name: cega-users
        image: nbisweden/ega-base
        imagePullPolicy: Always
        command: ["python3.6", "/cega/server.py"]
        env:
          - name: LEGA_INSTANCES
            value: lega
          - name: CEGA_REST_lega_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cega-creds
                key: credentials
        ports:
        - name: cega-users
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: cega-config
          mountPath: /cega
      volumes:
        - name: cega-config
          configMap:
            name: cega-users-config
            items:
              - key: users.html
                path: users.html
              - key: server.py
                path: server.py
              - key: ega-box-999.yml
                path: users/ega-box-999.yml
              - key: ega-box-999.yml
                path: users/lega/ega-box-999.yml
            defaultMode: 0744
