apiVersion: v1
kind: Service
metadata:
  name: cega-users
  labels:
    app: cega-users
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: cega-users
