apiVersion: v1
kind: Service
metadata:
  name: lega-keyserver
  namespace: localega
  labels:
    app: lega-keyserver
spec:
  ports:
  - port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app: lega-keyserver
