server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    secure-port-enabled: true
    non-secure-port-enabled: true
    lease-renewal-interval-in-seconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/

spring:
  application:
    name: eureka-server
