apiVersion: v1
kind: PersistentVolume
metadata:
  name: localega-db-pv
  labels:
    type: local
spec:
  storageClassName: postgres
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/db"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: localega-inbox-pv
  labels:
    type: local
spec:
  storageClassName: inbox
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/inbox"
