apiVersion: v1
kind: Secret
metadata:
  name: lega-db-secret
type: Opaque
data:
  postgres_password: <change me>
---
apiVersion: v1
kind: Secret
metadata:
  name: lega-password
type: Opaque
data:
  password: <change me>
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-keys
type: Opaque
data:
  access_key: <change me>
  secret_key: <change me>
---
apiVersion: v1
kind: Secret
metadata:
  name: cega-creds
type: Opaque
data:
  credentials: <change me>
  # secret_key: <change me>
