#!/usr/bin/env bash
set -e

echomsg "Generating fake Central EGA users"

[[ -x $(readlink ${OPENSSL}) ]] && echo "${OPENSSL} is not executable. Adjust the setting with --openssl" && exit 3

mkdir -p ${PRIVATE}/cega/users/pgp

EGA_USER_PASSWORD_JOHN=$(generate_password 16)
EGA_USER_PASSWORD_JANE=$(generate_password 16)
EGA_USER_PASSWORD_TAYLOR=$(generate_password 16)

EGA_USER_PUBKEY_JOHN=${PRIVATE}/cega/users/john.pub
EGA_USER_SECKEY_JOHN=${PRIVATE}/cega/users/john.sec

EGA_USER_PUBKEY_JANE=${PRIVATE}/cega/users/jane.pub
EGA_USER_SECKEY_JANE=${PRIVATE}/cega/users/jane.sec

${OPENSSL} genrsa -out ${EGA_USER_SECKEY_JOHN} -passout pass:${EGA_USER_PASSWORD_JOHN} 2048
${OPENSSL} rsa -in ${EGA_USER_SECKEY_JOHN} -passin pass:${EGA_USER_PASSWORD_JOHN} -pubout -out ${EGA_USER_PUBKEY_JOHN}
chmod 400 ${EGA_USER_SECKEY_JOHN}

${OPENSSL} genrsa -out ${EGA_USER_SECKEY_JANE} -passout pass:${EGA_USER_PASSWORD_JANE} 2048
${OPENSSL} rsa -in ${EGA_USER_SECKEY_JANE} -passin pass:${EGA_USER_PASSWORD_JANE} -pubout -out ${EGA_USER_PUBKEY_JANE}
chmod 400 ${EGA_USER_SECKEY_JANE}

cat > ${PRIVATE}/cega/users/john.yml <<EOF
---
password_hash: $(${OPENSSL} passwd -1 ${EGA_USER_PASSWORD_JOHN})
pubkey: $(ssh-keygen -i -mPKCS8 -f ${EGA_USER_PUBKEY_JOHN})
EOF

cat > ${PRIVATE}/cega/users/jane.yml <<EOF
---
pubkey: $(ssh-keygen -i -mPKCS8 -f ${EGA_USER_PUBKEY_JANE})
EOF

cat > ${PRIVATE}/cega/users/taylor.yml <<EOF
---
password_hash: $(${OPENSSL} passwd -1 ${EGA_USER_PASSWORD_TAYLOR})
EOF

mkdir -p ${PRIVATE}/cega/users/{swe1,fin1}
chmod 777 ${PRIVATE}/cega/users/{swe1,fin1}
# They all have access to SWE1
( # In a subshell
    cd ${PRIVATE}/cega/users/swe1
    ln -s ../john.yml .
    ln -s ../jane.yml .
    ln -s ../taylor.yml .
)
# John has also access to FIN1
(
    cd ${PRIVATE}/cega/users/fin1
    ln -s ../john.yml .
)

echomsg "Generating PGP keys for EGA users"

if [[ -f /tmp/generate_pgp_key.py ]]; then
    # Running in a container
    GEN_KEY="python3.6 /tmp/generate_pgp_key.py"
else
    # Running on host, outside a container
    GEN_KEY="python ${EXTRAS}/generate_pgp_key.py"
fi

${GEN_KEY} "John Travolta" "john@ega.eu" "John" --passphrase "hi-john" --pub ${PRIVATE}/cega/users/pgp/john.pub --priv ${PRIVATE}/cega/users/pgp/john.sec --armor
chmod 644 ${PRIVATE}/cega/users/pgp/john.pub

${GEN_KEY} "Jane Fonda" "jane@ega.eu" "Jane" --passphrase "hi-jane" --pub ${PRIVATE}/cega/users/pgp/jane.pub --priv ${PRIVATE}/cega/users/pgp/jane.sec --armor
chmod 644 ${PRIVATE}/cega/users/pgp/jane.pub

${GEN_KEY} "Taylor Swift" "taylor@ega.eu" "Taylor" --passphrase "hi-taylor" --pub ${PRIVATE}/cega/users/pgp/taylor.pub --priv ${PRIVATE}/cega/users/pgp/taylor.sec --armor
chmod 644 ${PRIVATE}/cega/users/pgp/taylor.pub


cat >> ${PRIVATE}/cega/.trace <<EOF
#####################################################################
#
# Generated by bootstrap/lib/cega_users.sh
#
#####################################################################
#
EGA_USER_PASSWORD_JOHN    = ${EGA_USER_PASSWORD_JOHN}
EGA_USER_PUBKEY_JOHN      = ./private/cega/users/john.pub
EGA_USER_PUBKEY_JANE      = ./private/cega/users/jane.pub
EGA_USER_PASSWORD_TAYLOR  = ${EGA_USER_PASSWORD_TAYLOR}
#
EGA_USER_PGP_JOHN         = ./private/cega/users/pgp/john.pub
EGA_USER_PGP_JANE         = ./private/cega/users/pgp/jane.pub
EGA_USER_PGP_TAYLOR       = ./private/cega/users/pgp/taylor.pub
# =============================
EOF

cat > ${PRIVATE}/cega.yml <<EOF
version: '3.2'

networks:
    # user overlay in swarm mode
    # default is bridge
  cega:
    driver: bridge

services:

  ############################################
  # Faking Central EGA
  ############################################
  cega-mq:
    hostname: cega-mq
    ports:
      - "15670:15672"
      - "5672:5672"
    image: rabbitmq:3.6.14-management
    container_name: cega-mq
    volumes:
       - ./cega/mq/defs.json:/etc/rabbitmq/defs.json:ro
       - ./cega/mq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    restart: on-failure:3
    networks:
      - cega

  cega-users:
    env_file: cega/env
    image: nbisweden/ega-base
    hostname: cega-users
    container_name: cega-users
    #ports:
    #  - "9100:80"
    expose:
      - "80"
    volumes:
      - ./cega/users:/cega/users:rw
      - ../images/cega/users.html:/cega/users.html
      - ../images/cega/server.py:/cega/server.py
      # - ../..:/root/.local/lib/python3.6/site-packages:ro
    restart: on-failure:3
    networks:
      - cega
    command: ["python3.6", "/cega/server.py"]

  ############################################
  # Fake Eureka server
  ############################################
  cega-eureka:
    hostname: cega-eureka
    #ports:
    #  - "8761:8761"
    expose:
      - 8761
    image: nbisweden/ega-base
    container_name: cega-eureka
    volumes:
      - ../images/cega/eureka.py:/cega/eureka.py
    restart: on-failure:3
    networks:
      - cega
    command: ["python3.6", "/cega/eureka.py"]
EOF

# For the compose file
echo -n "private/cega.yml" >> ${DOT_ENV} # no newline
