version: '3.3'

networks:

  cega:
    driver: overlay

services:

  cega-mq:
    hostname: cega-mq
    ports:
      - "15670:15672"
      - "5672:5672"
    image: rabbitmq:3.6.14-management
    deploy:
      restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3
              window: 120s
    networks:
      - cega
    configs:
      - source: cega.defs.json
        target: /etc/rabbitmq/defs.json
      - source: cega.rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config

  cega-users:
    image: nbisweden/ega-base
    hostname: cega-users
    deploy:
      restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3
              window: 120s
    networks:
      - cega
    environment:
      - LEGA_INSTANCES
      - CEGA_REST_lega_PASSWORD
    configs:
      - source: users.html
        target: /cega/users.html
      - source: server.py
        target: /cega/server.py
      - source: john.yml
        target: /cega/users/lega/john.yml
      - source: jane.yml
        target: /cega/users/lega/jane.yml
    command: ["python3.6", "/cega/server.py"]

  cega-eureka:
    hostname: cega-eureka
    image: nbisweden/ega-base
    deploy:
      restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 3
              window: 120s
    networks:
      - cega
    configs:
      - source: eureka.py
        target: /cega/eureka.py
    command: ["python3.6", "/cega/eureka.py"]

configs:
  cega.defs.json:
    external: true
  cega.rabbitmq.config:
    external: true
  eureka.py:
    external: true
  server.py:
    external: true
  users.html:
    external: true
  john.yml:
    external: true
  jane.yml:
    external: true