apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest
  labels:
    role: ingest
    app: LocalEGA
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingest
  template:
    metadata:
      labels:
        app: ingest
        role: ingest
    spec:
      containers:
      - name: ingest
        image: nbisweden/ega-base:latest
        imagePullPolicy: Always
        command: ["gosu", "lega", "ega-ingest"]
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lega-db-secret
              key: postgres_password
        - name: LEGA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lega-password
              key: password
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-keys
              key: access_key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-keys
              key: secret_key
        volumeMounts:
        - name: inbox
          mountPath: /ega/inbox
        - name: ingest-conf
          mountPath: /etc/ega
      restartPolicy: Always
      volumes:
      - name: ingest-conf
        configMap:
          name: lega-config
          items:
            - key: conf.ini
              path: conf.ini
          defaultMode: 0744
      - name: inbox
        persistentVolumeClaim:
          claimName: inbox-storage
