version: '3.2'

networks:
    # user overlay in swarm mode
    # default is bridge
  central_fake:
    driver: bridge

services:

  ############################################
  # Faking Central EGA
  ############################################
  cega-mq:
    hostname: cega-mq
    ports:
      - "15670:15672"
      - "5672:5672"
    image: rabbitmq:3.6.14-management
    container_name: cega-mq
    volumes:
       - ${DATA}/cega/mq/defs.json:/etc/rabbitmq/defs.json:ro
       - ${DATA}/cega/mq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    restart: on-failure:3
    networks:
      - central_fake

  cega-users:
    env_file: private/cega/env
    image: nbisweden/ega-cega-users
    hostname: cega-users
    container_name: cega-users
    ports:
      - "9100:80"
    volumes:
      - ${DATA}/cega/users:/cega/users:rw
      # - ../..:/root/.local/lib/python3.6/site-packages:ro
    restart: on-failure:3
    networks:
      - central_fake
