version: '3.2'

services:

  # Local Message broker
  mq_swe1:
    hostname: ega_mq
    ports:
      - "15672:15672"
    image: nbisweden/ega-mq
    container_name: ega_mq_swe1

  # Postgres Database for Sweden
  db_swe1:
    env_file: private/swe1/db.env
    hostname: ega_db_swe1
    container_name: ega_db_swe1
    image: nbisweden/ega-db

  # Postgres Database for Finland
  db_fin1:
    env_file: private/fin1/db.env
    hostname: ega_db_fin1
    container_name: ega_db_fin1
    image: nbisweden/ega-db

  # ReST frontend
  frontend_swe1:
    hostname: ega_frontend
    depends_on:
      - db_swe1
    ports:
      - "9000:80"
    expose:
      - 80
    container_name: ega_frontend_swe1
    image: nbisweden/ega-frontend
    volumes:
       - ${CONF_swe1}:/etc/ega/conf.ini:ro
       - ${LOG_swe1}:/etc/ega/logger.yml:ro

  # SFTP inbox for Sweden
  inbox_swe1:
    hostname: ega_inbox
    depends_on:
      - db_swe1
    env_file:
      - private/swe1/db.env
      - private/swe1/cega.env
    ports:
      - "${DOCKER_INBOX_swe1_PORT}:22"
    container_name: ega_inbox_swe1
    image: nbisweden/ega-inbox
    volumes:
       - inbox_swe1:/ega/inbox
       - ${CONF_swe1}:/etc/ega/conf.ini:ro
       - ${LOG_swe1}:/etc/ega/logger.yml:ro

  # SFTP inbox for Finland
  inbox_fin1:
    hostname: ega_inbox
    depends_on:
      - db_fin1
    env_file:
      - private/fin1/db.env
      - private/fin1/cega.env
    ports:
      - "${DOCKER_INBOX_fin1_PORT}:22"
    container_name: ega_inbox_fin1
    image: nbisweden/ega-inbox
    volumes:
       - inbox_fin1:/ega/inbox
       - ${CONF_fin1}:/etc/ega/conf.ini:ro
       - ${LOG_fin1}:/etc/ega/logger.yml:ro

  # Vault
  vault_swe1:
    depends_on:
      - db_swe1
      - mq_swe1
      - inbox_swe1
    hostname: ega_vault
    container_name: ega_vault_swe1
    image: nbisweden/ega-vault
    environment:
      - MQ_INSTANCE=ega_mq_swe1
    volumes:
       - staging_swe1:/ega/staging
       - vault_swe1:/ega/vault
       - ${CONF_swe1}:/etc/ega/conf.ini:ro
       - ${LOG_swe1}:/etc/ega/logger.yml:ro

  # Ingestion Workers
  ingest_swe1:
    depends_on:
      - db_swe1
      - mq_swe1
      - keys_swe1
      - inbox_swe1
    image: nbisweden/ega-worker
    environment:
      - GPG_TTY=/dev/console
      - MQ_INSTANCE=ega_mq_swe1
      - KEYSERVER_HOST=ega_keys_swe1
      - KEYSERVER_PORT=9010
    volumes:
       - inbox_swe1:/ega/inbox
       - staging_swe1:/ega/staging
       - ${CONF_swe1}:/etc/ega/conf.ini:ro
       - ${LOG_swe1}:/etc/ega/logger.yml:ro
       - ${SSL_CERT_swe1}:/etc/ega/ssl.cert:ro
       - ${GPG_HOME_swe1}/pubring.kbx:/root/.gnupg/pubring.kbx:ro
       - ${GPG_HOME_swe1}/trustdb.gpg:/root/.gnupg/trustdb.gpg

  # Key server
  keys_swe1:
    env_file: private/swe1/gpg.env
    environment:
      - GPG_TTY=/dev/console
      - KEYSERVER_PORT=9010
    hostname: ega_keys_swe1
    container_name: ega_keys_swe1
    image: nbisweden/ega-keys
    tty: true
    expose:
      - "9010"
      - "9011"
    volumes:
       - ${CONF_swe1}:/etc/ega/conf.ini:ro
       - ${LOG_swe1}:/etc/ega/logger.yml:ro
       - ${KEYS_swe1}:/etc/ega/keys.ini:ro
       - ${SSL_CERT_swe1}:/etc/ega/ssl.cert:ro
       - ${SSL_KEY_swe1}:/etc/ega/ssl.key:ro
       - ${GPG_HOME_swe1}/pubring.kbx:/root/.gnupg/pubring.kbx
       - ${GPG_HOME_swe1}/trustdb.gpg:/root/.gnupg/trustdb.gpg
       - ${GPG_HOME_swe1}/openpgp-revocs.d:/root/.gnupg/openpgp-revocs.d:ro
       - ${GPG_HOME_swe1}/private-keys-v1.d:/root/.gnupg/private-keys-v1.d:ro
       - ${RSA_SEC_swe1}:/etc/ega/rsa/sec.pem:ro
       - ${RSA_PUB_swe1}:/etc/ega/rsa/pub.pem:ro

  keys_fin1:
    env_file: private/fin1/gpg.env
    environment:
      - GPG_TTY=/dev/console
      - KEYSERVER_PORT=9010
    hostname: ega_keys_fin1
    container_name: ega_keys_fin1
    image: nbisweden/ega-keys
    tty: true
    expose:
      - "9010"
      - "9011"
    volumes:
       - ${CONF_fin1}:/etc/ega/conf.ini:ro
       - ${KEYS_fin1}:/etc/ega/keys.ini:ro
       - ${SSL_CERT_fin1}:/etc/ega/ssl.cert:ro
       - ${SSL_KEY_fin1}:/etc/ega/ssl.key:ro
       - ${GPG_HOME_fin1}/pubring.kbx:/root/.gnupg/pubring.kbx
       - ${GPG_HOME_fin1}/trustdb.gpg:/root/.gnupg/trustdb.gpg
       - ${GPG_HOME_fin1}/openpgp-revocs.d:/root/.gnupg/openpgp-revocs.d:ro
       - ${GPG_HOME_fin1}/private-keys-v1.d:/root/.gnupg/private-keys-v1.d:ro
       - ${RSA_SEC_fin1}:/etc/ega/rsa/sec.pem:ro
       - ${RSA_PUB_fin1}:/etc/ega/rsa/pub.pem:ro

  # # Error Monitors
  # monitors_swe1:
  #   # depends_on:
  #   #   - db_swe1
  #   ports:
  #     - "10514:10514"
  #   expose:
  #     - 10514
  #   hostname: ega_monitors_swe1
  #   container_name: ega_monitors_swe1
  #   image: nbisweden/ega-monitors

  ############################################
  # Faking Central EGA
  ############################################
  cega_mq:
    hostname: cega_mq
    ports:
      - "15673:15672"
    image: nbisweden/ega-cega_mq
    container_name: cega_mq
    volumes:
       - ${CEGA_MQ_DEFS}:/etc/rabbitmq/defs.json:ro

  cega_users:
    env_file: private/cega/env
    image: nbisweden/ega-cega_users
    container_name: cega_users
    ports:
      - "9100:80"
    volumes:
      - ${CEGA_USERS}:/cega/users:rw


# Use the default driver for volume creation
volumes:
  inbox_swe1:
  staging_swe1:
  vault_swe1:
  inbox_fin1:
  # staging_fin1:
  # vault_fin1:
