version: '3.2'

services:

  # Local Message broker
  mq_swe1:
    env_file: private/swe1/mq.env
    hostname: ega_mq
    ports:
      - "15672:15672"
    image: nbisweden/ega-mq
    container_name: ega_mq_swe1

  # Postgres Database for Sweden
  db_swe1:
    env_file: private/swe1/db.env
    hostname: ega_db_swe1
    container_name: ega_db_swe1
    image: postgres:latest
    volumes:
      - ${DATA}/swe1/db.sql:/docker-entrypoint-initdb.d/ega.sql:ro
      

  # Postgres Database for Finland
  db_fin1:
    env_file: private/fin1/db.env
    hostname: ega_db_fin1
    container_name: ega_db_fin1
    image: postgres:latest
    volumes:
      - ${DATA}/fin1/db.sql:/docker-entrypoint-initdb.d/ega.sql:ro

  # ReST frontend
  frontend_swe1:
    hostname: ega_frontend
    depends_on:
      - db_swe1
      - logstash_swe1
    ports:
      - "9000:80"
    expose:
      - 80
    container_name: ega_frontend_swe1
    image: nbisweden/ega-frontend
    volumes:
       - ${DATA}/swe1/ega.conf:/etc/ega/conf.ini:ro
       - ${DATA}/swe1/logger.yml:/etc/ega/logger.yml:ro
       - ../..:/root/.local/lib/python3.6/site-packages:ro

  # SFTP inbox for Sweden
  inbox_swe1:
    hostname: ega_inbox
    depends_on:
      - db_swe1
    env_file:
      - private/swe1/db.env
      - private/swe1/cega.env
    ports:
      - "${DOCKER_INBOX_swe1_PORT}:22"
    container_name: ega_inbox_swe1
    image: nbisweden/ega-inbox
    volumes:
       - inbox_swe1:/ega/inbox
       - ${DATA}/swe1/ega.conf:/etc/ega/conf.ini:ro
       - ${DATA}/swe1/logger.yml:/etc/ega/logger.yml:ro

  # SFTP inbox for Finland
  inbox_fin1:
    hostname: ega_inbox
    depends_on:
      - db_fin1
    env_file:
      - private/fin1/db.env
      - private/fin1/cega.env
    ports:
      - "${DOCKER_INBOX_fin1_PORT}:22"
    container_name: ega_inbox_fin1
    image: nbisweden/ega-inbox
    volumes:
       - inbox_fin1:/ega/inbox
       - ${DATA}/fin1/ega.conf:/etc/ega/conf.ini:ro
       - ${DATA}/fin1/logger.yml:/etc/ega/logger.yml:ro

  # Vault
  vault_swe1:
    depends_on:
      - db_swe1
      - mq_swe1
      - inbox_swe1
      - logstash_swe1
    hostname: ega_vault
    container_name: ega_vault_swe1
    image: nbisweden/ega-vault
    environment:
      - MQ_INSTANCE=ega_mq_swe1
    volumes:
       - staging_swe1:/ega/staging
       - vault_swe1:/ega/vault
       - ${DATA}/swe1/ega.conf:/etc/ega/conf.ini:ro
       - ${DATA}/swe1/logger.yml:/etc/ega/logger.yml:ro
       - ../..:/root/.local/lib/python3.6/site-packages:ro

  # Ingestion Workers
  ingest_swe1:
    depends_on:
      - db_swe1
      - mq_swe1
      - keys_swe1
      - inbox_swe1
      - logstash_swe1
    image: nbisweden/ega-worker
    environment:
      - GPG_TTY=/dev/console
      - MQ_INSTANCE=ega_mq_swe1
      - KEYSERVER_HOST=ega_keys_swe1
      - KEYSERVER_PORT=9010
    volumes:
       - inbox_swe1:/ega/inbox
       - staging_swe1:/ega/staging
       - ${DATA}/swe1/ega.conf:/etc/ega/conf.ini:ro
       - ${DATA}/swe1/logger.yml:/etc/ega/logger.yml:ro
       - ${DATA}/swe1/certs/ssl.cert:/etc/ega/ssl.cert:ro
       - ${DATA}/swe1/gpg/pubring.kbx:/root/.gnupg/pubring.kbx:ro
       - ${DATA}/swe1/gpg/trustdb.gpg:/root/.gnupg/trustdb.gpg
       - ../..:/root/.local/lib/python3.6/site-packages:ro

  # Key server
  keys_swe1:
    env_file: private/swe1/gpg.env
    depends_on:
      - logstash_swe1
    environment:
      - GPG_TTY=/dev/console
      - KEYSERVER_PORT=9010
    hostname: ega_keys_swe1
    container_name: ega_keys_swe1
    image: nbisweden/ega-keys
    tty: true
    expose:
      - "9010"
      - "9011"
    volumes:
       - ${DATA}/swe1/ega.conf:/etc/ega/conf.ini:ro
       - ${DATA}/swe1/logger.yml:/etc/ega/logger.yml:ro
       - ${DATA}/swe1/keys.conf:/etc/ega/keys.ini:ro
       - ${DATA}/swe1/certs/ssl.cert:/etc/ega/ssl.cert:ro
       - ${DATA}/swe1/certs/ssl.key:/etc/ega/ssl.key:ro
       - ${DATA}/swe1/gpg/pubring.kbx:/root/.gnupg/pubring.kbx
       - ${DATA}/swe1/gpg/trustdb.gpg:/root/.gnupg/trustdb.gpg
       - ${DATA}/swe1/gpg/openpgp-revocs.d:/root/.gnupg/openpgp-revocs.d:ro
       - ${DATA}/swe1/gpg/private-keys-v1.d:/root/.gnupg/private-keys-v1.d:ro
       - ${DATA}/swe1/rsa/ega.sec:/etc/ega/rsa/sec.pem:ro
       - ${DATA}/swe1/rsa/ega.pub:/etc/ega/rsa/pub.pem:ro
       - ../..:/root/.local/lib/python3.6/site-packages:ro

  keys_fin1:
    env_file: private/fin1/gpg.env
    environment:
      - GPG_TTY=/dev/console
      - KEYSERVER_PORT=9010
    hostname: ega_keys_fin1
    container_name: ega_keys_fin1
    image: nbisweden/ega-keys
    tty: true
    expose:
      - "9010"
      - "9011"
    volumes:
       - ${DATA}/fin1/ega.conf:/etc/ega/conf.ini:ro
       - ${DATA}/fin1/logger.yml:/etc/ega/logger.yml:ro
       - ${DATA}/fin1/keys.conf:/etc/ega/keys.ini:ro
       - ${DATA}/fin1/certs/ssl.cert:/etc/ega/ssl.cert:ro
       - ${DATA}/fin1/certs/ssl.key:/etc/ega/ssl.key:ro
       - ${DATA}/fin1/gpg/pubring.kbx:/root/.gnupg/pubring.kbx
       - ${DATA}/fin1/gpg/trustdb.gpg:/root/.gnupg/trustdb.gpg
       - ${DATA}/fin1/gpg/openpgp-revocs.d:/root/.gnupg/openpgp-revocs.d:ro
       - ${DATA}/fin1/gpg/private-keys-v1.d:/root/.gnupg/private-keys-v1.d:ro
       - ${DATA}/fin1/rsa/ega.sec:/etc/ega/rsa/sec.pem:ro
       - ${DATA}/fin1/rsa/ega.pub:/etc/ega/rsa/pub.pem:ro
       - ../..:/root/.local/lib/python3.6/site-packages:ro

  ############################################
  # Faking Central EGA
  ############################################
  cega_mq:
    hostname: cega_mq
    ports:
      - "15673:15672"
    image: nbisweden/ega-cega_mq
    container_name: cega_mq
    volumes:
       - ${DATA}/cega/mq/defs.json:/etc/rabbitmq/defs.json:ro

  cega_users:
    env_file: private/cega/env
    image: nbisweden/ega-cega_users
    container_name: cega_users
    ports:
      - "9100:80"
    volumes:
      - ${DATA}/cega/users:/cega/users:rw
      - ../..:/root/.local/lib/python3.6/site-packages:ro

  ############################################
  # Logging & Monitoring (ELK: Elasticsearch, Logstash, Kibana).
  # NB: can't use underscores for containers' names, because of Logstash issue.
  ############################################
  elasticsearch_swe1:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
    container_name: ega-elasticsearch-swe1
    volumes:
      - ${DATA}/swe1/logs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch_swe1:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash_swe1:
    image: docker.elastic.co/logstash/logstash-oss:6.0.0
    container_name: ega-logstash-swe1
    volumes:
      - ${DATA}/swe1/logs/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ${DATA}/swe1/logs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch_swe1

  kibana_swe1:
    image: docker.elastic.co/kibana/kibana-oss:6.0.0
    container_name: ega-kibana-swe1
    volumes:
      - ${DATA}/swe1/logs/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch_swe1

# Use the default driver for volume creation
volumes:
  inbox_swe1:
  staging_swe1:
  vault_swe1:
  elasticsearch_swe1:
  inbox_fin1:
  # staging_fin1:
  # vault_fin1:
