#!/usr/bin/env bash
set -e

OPENSSL=openssl
LEGA_INSTANCES="swe1,fin1"

declare -A CEGA_MQ
CEGA_MQ['swe1']=$(generate_password 16)
CEGA_MQ['fin1']=$(generate_password 16)

declare -A CEGA_REST
CEGA_REST['swe1']=$(generate_password 16)
CEGA_REST['fin1']=$(generate_password 16)

declare -A LEGA_GREETINGS
LEGA_GREETINGS['swe1']="Welcome to Local EGA Sweden @ NBIS"
LEGA_GREETINGS['fin1']="Welcome to Local EGA Finland @ CSC"
