apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inbox
  labels:
    role: inbox
    app: LocalEGA
spec:
  replicas: 1
  serviceName: inbox
  selector:
    matchLabels:
      app: inbox
  template:
    metadata:
      labels:
        app: inbox
        role: inbox
    spec:
      containers:
      - name: inbox
        image: nbisweden/ega-mina-inbox:latest
        imagePullPolicy: Always
        env:
        - name: BROKER_HOST
          valueFrom:
            configMapKeyRef:
              name: lega-inbox
              key: broker
        - name: INBOX_PORT
          value: "2222"
        - name: CEGA_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: lega-inbox
              key: cega_endpoint
        - name: CEGA_ENDPOINT_CREDS
          valueFrom:
            secretKeyRef:
              name: cega-creds
              key: credentials
        ports:
        - name: inbox
          containerPort: 2222
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 20
        volumeMounts:
        - name: lega-inbox
          mountPath: /ega/inbox
      # restartPolicy: Always
      volumes:
      - name: lega-inbox
        persistentVolumeClaim:
          claimName: inbox-storage
