{"rabbit_version":"3.6.11",
 "users":[{"name":"__CEGA_MQ_USER__", "password_hash":"__CEGA_MQ_PASSWORD_HASH__", "hashing_algorithm":"rabbit_password_hashing_sha256", "tags":"administrator"}],
 "vhosts":[{"name":"/"}, {"name":"test"}],
 "permissions":[{"user":"__CEGA_MQ_USER__" , "vhost":"/", "configure":".*", "write":".*", "read":".*"}],
 "parameters":[],
 "global_parameters":[{"name":"cluster_name", "value":"rabbit@localhost"}],
 "policies":[],
 "queues":[{"name":"sweden.v1.commands.file"     , "vhost":"test", "durable":true, "auto_delete":false, "arguments":{}},
	   {"name":"sweden.v1.commands.account"  , "vhost":"test", "durable":true, "auto_delete":false, "arguments":{}},
	   {"name":"sweden.v1.commands.completed", "vhost":"test", "durable":true, "auto_delete":false, "arguments":{}},
	   {"name":"sweden.v1.commands.user"     , "vhost":"test", "durable":true, "auto_delete":false, "arguments":{}}],
 "exchanges":[{"name":"localega.v1", "vhost":"test", "type":"topic", "durable":true, "auto_delete":false, "internal":false, "arguments":{}}],
 "bindings":[{"source":"localega.v1", "vhost":"test", "destination_type":"queue", "arguments":{},
	      "destination":"sweden.v1.commands.file", "routing_key":"sweden.file"},
	     {"source":"localega.v1", "vhost":"test", "destination_type":"queue", "arguments":{},
	      "destination":"sweden.v1.commands.completed", "routing_key":"sweden.file.completed"},
	     {"source":"localega.v1", "vhost":"test", "destination_type":"queue", "arguments":{},
	      "destination":"sweden.v1.commands.user", "routing_key":"sweden.user"},
	     {"source":"localega.v1", "vhost":"test", "destination_type":"queue", "arguments":{},
	      "destination":"sweden.v1.commands.account", "routing_key":"sweden.user.account"}]
}
