version: 1
root:
  level: NOTSET
  handlers: [noHandler]

loggers:
  lega:
    level: INFO
    handlers: [console]
    propagate: true
    qualname: lega

handlers:
  noHandler:
    class: logging.NullHandler
    level: NOTSET
  console:
    class: logging.StreamHandler
    formatter: lega
    stream: ext://sys.stderr

formatters:
  lega:
    format: '[{asctime:<20}][{name}][{process:d} {processName:>15}][{levelname}] (L:{lineno}) {funcName}: {message}'
    style: '{'
    datefmt: '%Y-%m-%d %H:%M:%S'
