version: 1
root:
  level: NOTSET
  handlers: [noHandler]

loggers:
  lega:
    level: INFO
    handlers: [syslog,mainFile]
    propagate: true
    qualname: lega

handlers:
  noHandler:
    class: logging.NullHandler
    level: NOTSET
  mainFile:
    class: logging.FileHandler
    formatter: lega
    filename: '/tmp/ega.log'
    mode: 'w'
  syslog:
    class: logging.handlers.SysLogHandler
    address: !!python/tuple ['ega-db', 514]
    formatter: lega
    facility: 'local1'
    # socktype: socket.SOCK_STREAM # for tcp. Defaults to udp

formatters:
  lega:
    format: '[{asctime:<20}][{name}][{process:d} {processName:>15}][{levelname}] (L:{lineno}) {funcName}: {message}'
    style: '{'
    datefmt: '%Y-%m-%d %H:%M:%S'
