apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lega-verify
  namespace: localega
  labels:
    role: verify
spec:
  replicas: 1
  serviceName: "lega-verify"
  selector:
    matchLabels:
      app: lega-verify
  template:
    metadata:
      labels:
        app: lega-verify
        role: verify
    spec:
      containers:
      - name: verify
        image: nbisweden/ega-base:latest
        imagePullPolicy: Always
        command: ["gosu", "lega", "ega-verify"]
        env:
          - name: LEGA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lega-password
                key: password
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-keys
                key: access_key
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: s3-keys
                key: secret_key
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-keys
                key: access_key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-keys
                key: secret_key
        volumeMounts:
        - name: verify-conf
          mountPath: /etc/ega
      restartPolicy: Always
      volumes:
      - name: verify-conf
        configMap:
          name: lega-config
          items:
            - key: ega.conf
              path: conf.ini
          defaultMode: 0744
