#!/usr/bin/env bash
set -e

DOCKER_PORT_inbox=2223
DOCKER_PORT_mq=15673
DOCKER_PORT_kibana=5602

LEGA_GREETINGS="Welcome to Local EGA Finland @ CSC"
CEGA_MQ_PASSWORD=$(generate_password 16)
CEGA_REST_PASSWORD=$(generate_password 16)

SSL_SUBJ="/C=FI/ST=Finland/L=Helsinki/O=CSC/OU=SysDevs/CN=LocalEGA/emailAddress=ega@csc.fi"

DB_USER=lega
DB_PASSWORD=$(generate_password 16)
DB_TRY=30

GPG_NAME="EGA Finland"
GPG_COMMENT="@CSC"
GPG_EMAIL="ega@csc.fi"
GPG_PASSPHRASE=$(generate_password 16)

LOG_LEVEL=INFO
