apiVersion: v1
kind: Service
metadata:
  name: inbox
  labels:
    app: inbox
spec:
  type: NodePort
  ports:
  - port: 2222
    targetPort: 2222
    protocol: TCP
    name: inbox
  selector:
    app: inbox
